# Data Programming in Python | BAIS:6040
# Homework 4. Files and Pandas

## File Handling Questions (15 points)

You have a dataframe `df` with the features of diamonds.

In [9]:
# Do not make any change to this cell. Just run this cell.
import os
#from seaborn import load_dataset

#Importing pandas as pd
import pandas as pd

#df_stock = pd.read_csv("Q1_FAANG_Final.csv")
df_diamonds = pd.read_csv("hw_diamonds-1.csv")
df_diamonds

      carat/cut/color/clarity/depth/table/price
0                0.23/Ideal/E/SI2/61.5/55.0/326
1              0.21/Premium/E/SI1/59.8/61.0/326
2                 0.23/Good/E/VS1/56.9/65.0/327
3              0.29/Premium/I/VS2/62.4/58.0/334
4                 0.31/Good/J/SI2/63.3/58.0/335
...                                         ...
53935           0.72/Ideal/D/SI1/60.8/57.0/2757
53936            0.72/Good/D/SI1/63.1/55.0/2757
53937        0.7/Very Good/D/SI1/62.8/60.0/2757
53938         0.86/Premium/H/SI2/61.0/58.0/2757
53939           0.75/Ideal/D/SI2/62.2/55.0/2757

[53940 rows x 1 columns]

1\. (5 pt) Create a CSV file named `hw_diamonds.csv` in the `outcome` directory. The file contains 7 column names `carat`, `cut`, `color`, `clarity`, `depth`, `table`, and `price` in the first row and the values from the corresponding columns of `df` in the following rows. The delimiter is a slash (/) for columns and a new line (\n) for rows. For example, the first 3 rows in the file must look as below. Do not use pandas.to_csv. Hint - loop through each row of the dataframe above using df.iterrows(). Use format printing .format or f-strings. https://www.geeksforgeeks.org/python/python-output-formatting/

carat/cut/color/clarity/depth/table/price
0.23/Ideal/E/SI2/61.5/55.0/326
0.21/Premium/E/SI1/59.8/61.0/326

In [12]:
# Your answer here
columns = ['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price']
with open("outcome/hw_diamonds.csv", 'w') as f:
    # Write header
    f.write('/'.join(columns) + '\n')

    # Loop through each row in the DataFrame
    for index, row in f.iterrows():
        # Create a slash-separated string of values from the specified columns
        f.write('/'.join(parts) + '\n')

AttributeError: '_io.TextIOWrapper' object has no attribute 'iterrows'

In [14]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
os.path.isfile("outcome/hw_diamonds.csv")                # Expected output: True

True

2\. (5 pt) Read the file `hw_diamonds.csv` created in Question 1 and print the first 10 rows in the file including the header row, separated by a comma (,) between columns. For example, the output must be printed as below. Do not use Pandas to read in the file.

carat,cut,color,clarity,depth,table,price
0.23,Ideal,E,SI2,61.5,55.0,326
0.21,Premium,E,SI1,59.8,61.0,326
0.23,Good,E,VS1,56.9,65.0,327
0.29,Premium,I,VS2,62.4,58.0,334
0.31,Good,J,SI2,63.3,58.0,335
0.24,Very Good,J,VVS2,62.8,57.0,336
0.24,Very Good,I,VVS1,62.3,57.0,336
0.26,Very Good,H,SI1,61.9,55.0,337
0.22,Fair,E,VS2,65.1,61.0,337

In [19]:
# Your answer here
fh = open('hw_diamonds-1.csv')

with open("hw_diamonds-1.csv", "r") as fh:
    lines = fh.readlines()
    for line in lines[1:10]:
        parts = line.rstrip('\n').split('/')
        print(','.join(parts))

0.23,Ideal,E,SI2,61.5,55.0,326
0.21,Premium,E,SI1,59.8,61.0,326
0.23,Good,E,VS1,56.9,65.0,327
0.29,Premium,I,VS2,62.4,58.0,334
0.31,Good,J,SI2,63.3,58.0,335
0.24,Very Good,J,VVS2,62.8,57.0,336
0.24,Very Good,I,VVS1,62.3,57.0,336
0.26,Very Good,H,SI1,61.9,55.0,337
0.22,Fair,E,VS2,65.1,61.0,337

3\. (5 pt) Create a list `diamonds`, in which each element is a dictionary with 3 keys being `carat`, `cut`, and `color` and the values being their corresponding values in `df`. For example, the first element in `diamonds` must look as below. Then, serialize the first 1,000 items in `diamonds` as a JSON formatted stream to a file named `hw_diamonds.json` saved in the `outcome` directory.

{'carat': 0.23, 'cut': 'Ideal', 'color': 'E'}

In [24]:
# Your answer here
diamonds = []

for _, row in hw_diamonds-1.csv.iterrows():
    diamonds.append({
        'carat': row['carat'],
        'cut': row['cut'],
        'color': row['color']
    })

SyntaxError: invalid decimal literal (4176701973.py, line 4)

In [ ]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
diamonds[0]

In [ ]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
len(diamonds)                                          # Expected output: 53940

In [ ]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
os.path.isfile("outcome/hw_diamonds.json")                # Expected output: True

## Pandas Questions (15 points)

You have a dataframe `df` in which each row refers to some features of a diamond such as carat, cut, color, clarity, depth, table, price, x, y, and z.

In [44]:
# # Do not make any change to this cell. Just run this cell.
# import numpy as np
# from seaborn import load_dataset

# df = load_dataset("diamonds")
# np.random.seed(0)
# df.iloc[np.random.randint(0, len(df), 10), :] = None

df_diamonds = pd.read_csv("hw_diamonds.csv", sep='/', header=0)

1\. Get the list of column names of `df` and save it in the variable `ans1`. The type of the list does not have to be the primitive Python list.

In [37]:
# Your answer here
# with open("hw_diamonds.csv", "r") as f:
#     header = f.readline().strip()        # read first line
#     ans1 = header.split("/")             # split into list

# print(ans1)

ans1 = list(df_diamonds.columns)

In [38]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
ans1

['carat/cut/color/clarity/depth/table/price']

2\. Select the first 10 rows from `df` and save the resulting dataframe in the variable `ans2`.

In [39]:
# Your answer here

ans2 = df_diamonds.head(10)

In [40]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
ans2

  carat/cut/color/clarity/depth/table/price
0            0.23/Ideal/E/SI2/61.5/55.0/326
1          0.21/Premium/E/SI1/59.8/61.0/326
2             0.23/Good/E/VS1/56.9/65.0/327
3          0.29/Premium/I/VS2/62.4/58.0/334
4             0.31/Good/J/SI2/63.3/58.0/335
5       0.24/Very Good/J/VVS2/62.8/57.0/336
6       0.24/Very Good/I/VVS1/62.3/57.0/336
7        0.26/Very Good/H/SI1/61.9/55.0/337
8             0.22/Fair/E/VS2/65.1/61.0/337
9        0.23/Very Good/H/VS1/59.4/61.0/338

3\.  Select all values in the `cut` column and save the resulting series in the variable `ans3`.

In [45]:
# Your answer here
ans3 = df_diamonds['cut']

In [46]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
ans3

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: cut, Length: 53940, dtype: str

4\. Select all rows in `df` that meet all the following three conditions: the cut is *Premium*, the color is *G*, and the price is greater than 10,000. Save the resulting dataframe in the variable `ans4`.

In [47]:
# Your answer here

ans4 = df_diamonds[(df_diamonds['cut'] == 'Premium') &
          (df_diamonds['color'] == 'G') &
          (df_diamonds['price'] > 10000)]

In [48]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
ans4

       carat      cut color clarity  depth  table  price
21939   1.35  Premium     G     VS1   62.1   59.0  10012
21951   1.51  Premium     G     SI1   58.7   60.0  10020
21953   1.51  Premium     G     SI1   60.6   58.0  10020
21954   1.51  Premium     G     SI1   59.7   58.0  10020
21955   1.51  Premium     G     SI1   62.0   58.0  10020
...      ...      ...   ...     ...    ...    ...    ...
27670   2.03  Premium     G     VS2   59.6   60.0  18680
27680   2.01  Premium     G     SI2   61.2   57.2  18705
27687   1.70  Premium     G    VVS2   59.8   59.0  18718
27689   1.72  Premium     G    VVS2   61.8   60.0  18730
27725   2.01  Premium     G     SI1   60.3   59.0  18741

[365 rows x 7 columns]

5\. Select all rows in `df` that have any null values. Save the resulting dataframe in the variable `ans5`.

In [51]:
# Your answer here???
ans5 = df_diamonds[df_diamonds.isnull().any(axis=1)]

In [52]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)???
ans5

Empty DataFrame
Columns: [carat, cut, color, clarity, depth, table, price]
Index: []

6\. Fill all the null values in `df` such that the last non-null observations are propagated forward. Make sure to update `df`.

In [ ]:
# Your answer here

In [ ]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
df.info()

7\. Get the mean carat,	mean depth, mean table, and mean price of all diamonds and save them in the variables `ans7_1`, `ans7_2`, `ans7_3`, and `ans7_4`, respectively.

In [54]:
# Your answer here
ans7_1 = df_diamonds['carat'].mean()   # mean carat
ans7_2 = df_diamonds['depth'].mean()   # mean depth
ans7_3 = df_diamonds['table'].mean()   # mean table
ans7_4 = df_diamonds['price'].mean()   # mean price

In [55]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
ans7_1, ans7_2, ans7_3, ans7_4

(np.float64(0.7979397478680015),
 np.float64(61.74940489432702),
 np.float64(57.45718390804598),
 np.float64(3932.799721913237))

8\. Get the mean carat, mean depth, mean table, and mean price of premium-cut diamonds and save them in the variables `ans8_1`, `ans8_2`, `ans8_3`, and `ans8_4`, respectively.

In [56]:
# Your answer here

premium_df = df_diamonds[df_diamonds['cut'] == 'Premium']

ans8_1 = premium_df['carat'].mean()   # mean carat
ans8_2 = premium_df['depth'].mean()   # mean depth
ans8_3 = premium_df['table'].mean()   # mean table
ans8_4 = premium_df['price'].mean()   # mean price

In [57]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
ans8_1, ans8_2, ans8_3, ans8_4

(np.float64(0.8919548981219636),
 np.float64(61.26467261257341),
 np.float64(58.74609527953013),
 np.float64(4584.2577042999055))

9\. Group `df` by `color` to get the mean price for each color. Save the resulting series in the variable `ans9`.

In [58]:
# Your answer here
ans9 = df_diamonds.groupby('color')['price'].mean()

In [59]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
ans9

color
D    3169.954096
E    3076.752475
F    3724.886397
G    3999.135671
H    4486.669196
I    5091.874954
J    5323.818020
Name: price, dtype: float64

10\. Sort the `df` by the columns `carat` and `price` both in ascending order, but do not change `df`. Save the resulting dataframe in the variable `ans10`.

In [61]:
# Your answer here
ans10 = df_diamonds.sort_values(by=['carat', 'price'], ascending=[True, True])

In [62]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
ans10

       carat      cut color clarity  depth  table  price
14      0.20  Premium     E     SI2   60.2   62.0    345
31591   0.20  Premium     E     VS2   59.8   62.0    367
31592   0.20  Premium     E     VS2   59.0   60.0    367
31593   0.20  Premium     E     VS2   61.1   59.0    367
31594   0.20  Premium     E     VS2   59.7   62.0    367
...      ...      ...   ...     ...    ...    ...    ...
25998   4.01  Premium     I      I1   61.0   61.0  15223
25999   4.01  Premium     J      I1   62.5   62.0  15223
27130   4.13     Fair     H      I1   64.8   61.0  17329
27630   4.50     Fair     J      I1   65.8   58.0  18531
27415   5.01     Fair     J      I1   65.5   59.0  18018

[53940 rows x 7 columns]