# Data Programming in Python | BAIS:6040
# Module 7
# Homework 6. Machine Learning

## Instructions

- Fill in the Python statements needed to complete all the questions below. 
- Program everything inside this notebook. 
- Use only one cell per question. 
- Each code cell must be run with no errors.
- Do not contain any unnecessary code in your answer. (Only the final outcome will be regarded as your answer.)
- If the question requests that you store information in a certain variable, use the specific variables name (case sensitive).
- All problems must be solved in a programmable way.
- When you are done, make sure to save your notebook and then click Restart & Run All before subimission to create a clean version.

#

## Machine Learning Regression Questions (14 points)

You have a dataframe `dfdi` with the features of diamonds.

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from scipy import stats
from sklearn import metrics

In [2]:
# Do not make any change to this cell. Just run this cell.
from seaborn import load_dataset

dfdi = load_dataset("diamonds")
dfdi

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

For questions 1 to 6, using the diamond data, we aim to build a <b>regression</b> model that is able to predict the price of a new diamond based on its carat, cut, color, clarity, depth, table, x, y, and z.

1\. There are 3 categorical columns in `dfdi` as shown below: `cut`, `color`, and `clarity`.

In [5]:
dfdi.cut.value_counts().sort_index() #Sort diamonds by categorical column cut

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [6]:
dfdi.color.value_counts().sort_index() #Sort diamonds by categorical column color

color
D     6775
E     9797
F     9542
G    11292
H     8304
I     5422
J     2808
Name: count, dtype: int64

In [7]:
dfdi.clarity.value_counts().sort_index() #Sort diamonds by categorical column clarity

clarity
IF       1790
VVS1     3655
VVS2     5066
VS1      8171
VS2     12258
SI1     13065
SI2      9194
I1        741
Name: count, dtype: int64

Convert those categorical columns into numerical ones.

This conversion is shown in the cell below. You do not need to change it.

In [8]:
# Your answer here
cut_mapping = {'Fair': 0, 'Good': 1, 'Very Good': 2, 'Premium': 3, 'Ideal': 4}
color_mapping = {'J': 0, 'I': 1, 'H': 2, 'G': 3, 'F': 4, 'E': 5, 'D': 6}
clarity_mapping = {'I1': 0, 'SI2': 1, 'SI1': 2, 'VS2': 3, 'VS1': 4, 'VVS2': 5, 'VVS1': 6, 'IF': 7}

dfdi['cut'] = dfdi['cut'].apply(lambda x: cut_mapping[x])
dfdi['color'] = dfdi['color'].apply(lambda x: color_mapping[x])
dfdi['clarity'] = dfdi['clarity'].apply(lambda x: clarity_mapping[x])

In [9]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
dfdi[["cut", "color", "clarity"]]

      cut color clarity
0       4     5       1
1       3     5       2
2       1     5       4
3       3     1       3
4       1     0       1
...    ..   ...     ...
53935   4     6       2
53936   1     6       2
53937   2     6       2
53938   3     2       1
53939   4     6       1

[53940 rows x 3 columns]

In [11]:
type(cut_mapping)
type(color_mapping)
type(clarity_mapping)

dict

2\. According to the goal description above, there are nine features and one target for our prediction model. Based on those features and target, define the two variables `X` as the features set and `y` as the target set.

In [14]:
# Your answer here
features = ["carat", "cut", "color", "clarity", "depth", "table", "x", "y", "z"] #Predictor variables, X
target = ["price"] #Target variable y

In [15]:
X = dfdi[features]
y = dfdi[target]

In [16]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
X

       carat cut color clarity  depth  table     x     y     z
0       0.23   4     5       1   61.5   55.0  3.95  3.98  2.43
1       0.21   3     5       2   59.8   61.0  3.89  3.84  2.31
2       0.23   1     5       4   56.9   65.0  4.05  4.07  2.31
3       0.29   3     1       3   62.4   58.0  4.20  4.23  2.63
4       0.31   1     0       1   63.3   58.0  4.34  4.35  2.75
...      ...  ..   ...     ...    ...    ...   ...   ...   ...
53935   0.72   4     6       2   60.8   57.0  5.75  5.76  3.50
53936   0.72   1     6       2   63.1   55.0  5.69  5.75  3.61
53937   0.70   2     6       2   62.8   60.0  5.66  5.68  3.56
53938   0.86   3     2       1   61.0   58.0  6.15  6.12  3.74
53939   0.75   4     6       1   62.2   55.0  5.83  5.87  3.64

[53940 rows x 9 columns]

In [17]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
y

       price
0        326
1        326
2        327
3        334
4        335
...      ...
53935   2757
53936   2757
53937   2757
53938   2757
53939   2757

[53940 rows x 1 columns]

3\. Split `X` and `y` into 80% of training sets `X_train` and `y_train` and 20% of test sets `X_test` and `y_test`. Set  `random_state` to 0.

In [20]:
# Your answer here
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) #80% is training data, 20% is testing data

In [22]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
X_train.shape, y_train.shape, X_test.shape, y_test.shape #(Rows, Columns) per array

((43152, 9), (43152, 1), (10788, 9), (10788, 1))

4\. Initialize a linear regression model object `lr` and fit the model using the two training sets.

In [23]:
# Your answer here
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

In [25]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
lr.fit(X_train, y_train)

LinearRegression()

In [26]:
lr.score(X_train, y_train)

0.9063972348424985

In [27]:
lr.score(X_test, y_test)

0.9094252854685623

5\. Save the training score and test score in the variables `ans5_1` and `ans5_2`, respectively.

In [28]:
# Your answer here
ans5_1 = lr.score(X_train, y_train)
ans5_2 = lr.score(X_test, y_test)

In [29]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
ans5_1, ans5_2

(0.9063972348424985, 0.9094252854685623)

6\. Suppose there is a new diamond that has the following features. Using your linear regression model, how much would the price of the new diamond be? Save the predicted price in the variable `ans6`.

In [30]:
# Do not make any change to this cell. Just run this cell.
d = {"carat": 0.7,
     "cut": 4,
     "color": 1,
     "clarity": 5,
     "depth": 62.4,
     "table": 60.0,
     "x": 5.57,
     "y": 5.61,
     "z": 3.49}

new_diamond = [d["carat"], d["cut"], d["color"], d["clarity"], d["depth"], d["table"], d["x"], d["y"], d["z"]]
X_new = [new_diamond]
X_new

[[0.7, 4, 1, 5, 62.4, 60.0, 5.57, 5.61, 3.49]]

In [33]:
# Your answer here
ans6 = lr.predict(X_new)

/home/jrgoebel/.local/lib/python3.11/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [34]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
ans6

array([[3226.26842576]])

## Machine Learning Classification Questions (14 points)

In [62]:
from seaborn import load_dataset
dfc = load_dataset("mpg")
dfc

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

1\.	Change the origin column into 3 separate dummy variable columns ('usa', 'europe', 'japan')

In [63]:
#Answer here
dummies = pd.get_dummies(dfc['origin'], dtype=int)

2\.	Transform your mpg column into a new categorical variable mpg_level. If it is greater than the median of the column mpg_level = 1, otherwise mpg_level = 0.

In [64]:
#Answer here
dfc = pd.concat([dfc.drop(columns=['origin']), dummies], axis=1)

In [65]:
dfc.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,name,europe,japan,usa
0,18.0,8,307.0,130.0,3504,12.0,70,chevrolet chevelle malibu,0,0,1
1,15.0,8,350.0,165.0,3693,11.5,70,buick skylark 320,0,0,1
2,18.0,8,318.0,150.0,3436,11.0,70,plymouth satellite,0,0,1
3,16.0,8,304.0,150.0,3433,12.0,70,amc rebel sst,0,0,1
4,17.0,8,302.0,140.0,3449,10.5,70,ford torino,0,0,1

3\.	Using sklearn, split your dataset into an 80/20 training/testing split

In [66]:
#Answer here
from sklearn.model_selection import train_test_split

X = dfc.drop(columns=['mpg'])
y = dfc['mpg']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.20, random_state=0)

In [67]:
X_train

,cylinders,displacement,horsepower,weight,acceleration,model_year,name,europe,japan,usa
64,8,318.0,150.0,4135,13.5,72,plymouth fury iii,0,0,1
55,4,97.0,60.0,1834,19.0,71,volkswagen model 111,1,0,0
317,4,97.0,78.0,2188,15.8,80,audi 4000,1,0,0
102,4,97.0,46.0,1950,21.0,73,volkswagen super beetle,1,0,0
358,4,120.0,74.0,2635,18.3,81,mazda 626,0,1,0
...,...,...,...,...,...,...,...,...,...,...
323,4,156.0,105.0,2800,14.4,80,dodge colt,0,0,1
192,6,250.0,105.0,3353,14.5,76,chevrolet nova,0,0,1
117,4,68.0,49.0,1867,19.5,73,fiat 128,1,0,0
47,6,250.0,100.0,3282,15.0,71,pontiac firebird,0,0,1
172,4,90.0,71.0,2223,16.5,75,volkswagen dasher,1,0,0

In [68]:
y_train

64     15.0
55     27.0
317    34.3
102    26.0
358    31.6
       ...
323    27.9
192    22.0
117    29.0
47     19.0
172    25.0
Name: mpg, Length: 318, dtype: float64

In [69]:
X_test

,cylinders,displacement,horsepower,weight,acceleration,model_year,name,europe,japan,usa
65,8,351.0,153.0,4129,13.0,72,ford galaxie 500,0,0,1
132,4,140.0,75.0,2542,17.0,74,chevrolet vega,0,0,1
74,8,302.0,140.0,4294,16.0,72,ford gran torino (sw),0,0,1
78,4,120.0,87.0,2979,19.5,72,peugeot 504 (sw),1,0,0
37,6,232.0,100.0,3288,15.5,71,amc matador,0,0,1
...,...,...,...,...,...,...,...,...,...,...
269,4,105.0,75.0,2230,14.5,78,dodge omni,0,0,1
235,4,97.0,75.0,2265,18.2,77,toyota corolla liftback,0,1,0
145,4,83.0,61.0,2003,19.0,74,datsun 710,0,1,0
196,4,98.0,60.0,2164,22.1,76,chevrolet woody,0,0,1
124,8,350.0,180.0,3664,11.0,73,oldsmobile omega,0,0,1

In [70]:
y_test

65     14.0
132    25.0
74     13.0
78     21.0
37     18.0
       ...
269    30.9
235    26.0
145    32.0
196    24.5
124    11.0
Name: mpg, Length: 80, dtype: float64

In [71]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((318, 10), (318,), (80, 10), (80,))

## 4\. Perform the following 3 classification techniques using mpg_level as your target (y) variable and all the rest as your predictor (X) variables (do not include name and original mpg in your X variables).
###	Logistic Regression (max_iter = 1000)
###	KNN with neighbors = 7
###	Decision Tree (random_state = 1)

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from scipy import stats
from sklearn import metrics

In [132]:
dfc_clean = dfc.dropna()
dfc_clean['mpg_level'] = (dfc['mpg'] >= dfc['mpg'].median()).astype(int)
X = dfc_clean.drop(columns = ["name", "mpg", "mpg_level"]).values
y = dfc_clean["mpg_level"].values
dfc_clean

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,name,europe,japan,usa,mpg_level
0,18.0,8,307.0,130.0,3504,12.0,70,chevrolet chevelle malibu,0,0,1,0
1,15.0,8,350.0,165.0,3693,11.5,70,buick skylark 320,0,0,1,0
2,18.0,8,318.0,150.0,3436,11.0,70,plymouth satellite,0,0,1,0
3,16.0,8,304.0,150.0,3433,12.0,70,amc rebel sst,0,0,1,0
4,17.0,8,302.0,140.0,3449,10.5,70,ford torino,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,ford mustang gl,0,0,1,1
394,44.0,4,97.0,52.0,2130,24.6,82,vw pickup,1,0,0,1
395,32.0,4,135.0,84.0,2295,11.6,82,dodge rampage,0,0,1,1
396,28.0,4,120.0,79.0,2625,18.6,82,ford ranger,0,0,1,1
397,31.0,4,119.0,82.0,2720,19.4,82,chevy s-10,0,0,1,1

In [138]:
y_pred

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1])

In [133]:
#X_train = dfc_clean.drop(["name", "mpg"], axis=1).valuesa
#y_train = dfc_clean["mpg_level"].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) #80% is training data, 20% is testing data
log = LogisticRegression(max_iter=1000)

# Fit the classifier to the training data
log.fit(X_train, y_train)#learns the logistic regression equation/coefficients

y_pred = log.predict(X_test) #Outputs a 1 or 0 mpg_level
#linear regression would output continuous variable

# Print the accuracy
print(log.score(X_test, y_test)) #0.8734, accuracy score

print(classification_report(y_test, y_pred))

#precision: type1 vs type2 error,

/home/jrgoebel/.local/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8734177215189873
              precision    recall  f1-score   support

           0       0.94      0.81      0.87        42
           1       0.81      0.95      0.88        37

    accuracy                           0.87        79
   macro avg       0.88      0.88      0.87        79
weighted avg       0.88      0.87      0.87        79

/home/jrgoebel/.local/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [134]:
#Answer here
tree = DecisionTreeClassifier(random_state=0)

# Fit the classifier to the training data
tree.fit(X_train, y_train)

y_pred = tree.predict(X_test)

# Print the accuracy
print(tree.score(X_test, y_test))

print(classification_report(y_test, y_pred))

0.9240506329113924
              precision    recall  f1-score   support

           0       0.95      0.90      0.93        42
           1       0.90      0.95      0.92        37

    accuracy                           0.92        79
   macro avg       0.92      0.93      0.92        79
weighted avg       0.93      0.92      0.92        79

In [135]:
knn = KNeighborsClassifier(n_neighbors=7)

# Fit the classifier to the training data
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

# Print the accuracy
print(knn.score(X_test, y_test))

print(classification_report(y_test, y_pred))

0.8481012658227848
              precision    recall  f1-score   support

           0       0.92      0.79      0.85        42
           1       0.79      0.92      0.85        37

    accuracy                           0.85        79
   macro avg       0.85      0.85      0.85        79
weighted avg       0.86      0.85      0.85        79

# 5\. Using the training/testing (80/20) split and random_state = 1, evaluate the accuracy of all 3 models and the area under the ROC Curve, sklearn.metrics.roc_auc_score

In [136]:
#Answer here
from sklearn.model_selection import GridSearchCV
mod = GridSearchCV(
    estimator=MLPClassifier(hidden_layer_sizes=(4,), activation="tanh", max_iter=500, random_state=0), 
    param_grid={
        'hidden_layer_sizes': [(5,), (10,)],
        'max_iter': [200, 500, 1000],
        'activation': ["tanh", "relu"]
        
        },
        scoring='roc_auc',
    cv=5)

In [137]:
mod.fit(X,y)
results = pd.DataFrame(mod.cv_results_)
display(results)

/home/jrgoebel/.local/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/jrgoebel/.local/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/jrgoebel/.local/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/jrgoebel/.local/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/jrgoebel/.local/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_activation,param_hidden_layer_sizes,param_max_iter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.065363,0.007765,0.001891,0.000754,tanh,"(5,)",200,"{'activation': 'tanh', 'hidden_layer_sizes': (...",0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.000000,7
1,0.060851,0.006964,0.001412,0.000277,tanh,"(5,)",500,"{'activation': 'tanh', 'hidden_layer_sizes': (...",0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.000000,7
2,0.060093,0.008834,0.001605,0.000623,tanh,"(5,)",1000,"{'activation': 'tanh', 'hidden_layer_sizes': (...",0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.000000,7
3,0.081765,0.002279,0.001395,0.000140,tanh,"(10,)",200,"{'activation': 'tanh', 'hidden_layer_sizes': (...",0.985256,0.969231,0.906640,0.980276,0.941486,0.956578,0.029209,3
4,0.162362,0.016516,0.001408,0.000272,tanh,"(10,)",500,"{'activation': 'tanh', 'hidden_layer_sizes': (...",0.973718,0.977564,0.914859,0.979619,0.950033,0.959158,0.024557,1
5,0.162026,0.016521,0.001351,0.000096,tanh,"(10,)",1000,"{'activation': 'tanh', 'hidden_layer_sizes': (...",0.973718,0.977564,0.914859,0.979619,0.950033,0.959158,0.024557,1
6,0.005436,0.000032,0.001256,0.000018,relu,"(5,)",200,"{'activation': 'relu', 'hidden_layer_sizes': (...",0.921154,0.962179,0.896121,0.969757,0.918475,0.933537,0.027973,4
7,0.005405,0.000015,0.001255,0.000019,relu,"(5,)",500,"{'activation': 'relu', 'hidden_layer_sizes': (...",0.921154,0.962179,0.896121,0.969757,0.918475,0.933537,0.027973,4
8,0.005394,0.000007,0.001237,0.000013,relu,"(5,)",1000,"{'activation': 'relu', 'hidden_layer_sizes': (...",0.921154,0.962179,0.896121,0.969757,0.918475,0.933537,0.027973,4
9,0.005545,0.000016,0.001254,0.000012,relu,"(10,)",200,"{'activation': 'relu', 'hidden_layer_sizes': (...",0.005769,0.055128,0.106180,0.078895,0.071663,0.063527,0.033251,10
10,0.005555,0.000012,0.001230,0.000006,relu,"(10,)",500,"{'activation': 'relu', 'hidden_layer_sizes': (...",0.005769,0.055128,0.106180,0.078895,0.071663,0.063527,0.033251,10
11,0.005551,0.000017,0.001245,0.000013,relu,"(10,)",1000,"{'activation': 'relu', 'hidden_layer_sizes': (...",0.005769,0.055128,0.106180,0.078895,0.071663,0.063527,0.033251,10

Which model had the highest accuracy? Highest AUC?

In [ ]:
#Typed out answer here
#Decision tree accuracy was the highest
#Logistic Regression Accuracy: 0.87
#Decision Tree Accuracy: 0.92
#KNN Accuracy: 0.84