# Data Programming in Python | BAIS:6040
# Module 5 -  Data Manipulation and Analysis with NumPy and Pandas

## Exercises for Array Functions and Methods

Import the <b>numpy</b> package as `np`.

In [1]:
# Your answer here
import numpy as np

In [2]:
x = np.arange(1,37).reshape(6,6)

In [3]:
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

1\. Create a 5 x 5 array `x` of integers from 1 to 25, such that the first row of `x` has integers from 1 to 5, the second row from 6 to 10, and so on and so forth. (Hint: use <b>.arange<b> and <b>.reshape</b>.)

In [6]:
# Your answer here
x = np.arange(1,26).reshape(5,5) #np.arange last number is one before listed value

In [7]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

2\. Get a copy of `x` collapsed into one dimension.

In [12]:
# Your answer here
z = x.flatten()
print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]

3\. Get the min value in `x`.

In [13]:
# Your answer here
x.min()

np.int64(1)

4\. Get the index position of the max value in `x`.

In [11]:
# Your answer here
x.argmax()

np.int64(24)

5\. Negate `x` and save the result in `y`.

In [14]:
# Your answer here
y = -x
y

array([[ -1,  -2,  -3,  -4,  -5],
       [ -6,  -7,  -8,  -9, -10],
       [-11, -12, -13, -14, -15],
       [-16, -17, -18, -19, -20],
       [-21, -22, -23, -24, -25]])

6\. Calculate the element-wise addition of `x` and `y`.

In [15]:
# Your answer here
z = x + y
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Pandas Dataframes - aggregating, working with missing values, feature engineering

In [20]:
#Importing pandas as pd
import pandas as pd

In [21]:
#Read in FAANG csv file below using pd.read_csv() as df_stock
# "Q1_FAANG_Final.csv"
df_stock = pd.read_csv("Q1_FAANG_Final.csv")

### Create a new column called Daily_Change that looks at the percent change from Open => Close. This formula is (Open - close)/Open

In [24]:
df_stock['Daily_Change'] = (df_stock['Opening_Price'] - df_stock['Closing_Price']) / df_stock['Opening_Price']

In [25]:
df_stock

,Date,Ticker,Closing_Price,Opening_Price,Company Name,URL,StockDetails,Daily_Change
0,2026-01-02,AAPL,270.756653,272.005484,Apple Inc.,https://www.apple.com,https://finance.yahoo.com/quote/AAPL/,0.004591
1,2026-01-02,AMZN,226.500000,231.339996,"Amazon.com, Inc.",https://www.amazon.com,https://finance.yahoo.com/quote/AMZN/,0.020922
2,2026-01-02,GOOGL,315.149994,316.899994,Alphabet Inc. (Google LLC),https://www.abc.xyz,https://finance.yahoo.com/quote/GOOG/,0.005522
3,2026-01-02,META,650.409973,662.729980,"Meta Platforms, Inc.",https://www.meta.com,https://finance.yahoo.com/quote/META/,0.018590
4,2026-01-02,NFLX,90.989998,94.129997,"Netflix, Inc.",https://www.netflix.com,https://finance.yahoo.com/quote/NFLX/,0.033358
...,...,...,...,...,...,...,...,...
145,2026-02-13,AAPL,255.779999,262.010010,Apple Inc.,https://www.apple.com,https://finance.yahoo.com/quote/AAPL/,0.023778
146,2026-02-13,AMZN,198.789993,198.880005,"Amazon.com, Inc.",https://www.amazon.com,https://finance.yahoo.com/quote/AMZN/,0.000453
147,2026-02-13,GOOGL,305.720001,307.730011,Alphabet Inc. (Google LLC),https://www.abc.xyz,https://finance.yahoo.com/quote/GOOG/,0.006532
148,2026-02-13,META,639.770020,645.099976,"Meta Platforms, Inc.",https://www.meta.com,https://finance.yahoo.com/quote/META/,0.008262
149,2026-02-13,NFLX,76.870003,76.139999,"Netflix, Inc.",https://www.netflix.com,https://finance.yahoo.com/quote/NFLX/,-0.009588

### Use .loc in order to just get the Date, Ticker, and Daily_Change columns. Save this as df_copy

In [27]:
df_copy = df_stock.loc[1:10,['Date','Ticker','Daily_Change']] #Rows 1-10, : All rows
df_copy

          Date Ticker  Daily_Change
1   2026-01-02   AMZN      0.020922
2   2026-01-02  GOOGL      0.005522
3   2026-01-02   META      0.018590
4   2026-01-02   NFLX      0.033358
5   2026-01-05   AAPL      0.012489
6   2026-01-05   AMZN     -0.018441
7   2026-01-05  GOOGL      0.003526
8   2026-01-05   META     -0.011951
9   2026-01-05   NFLX     -0.005939
10  2026-01-06   AAPL      0.017378

### With df_copy use dataframe filtering to get only rows that have Netflix as their stock. Save this as df_net

In [30]:
#toms = actors_df[ actors_df['First Name'] == 'Tom' ]  See example for help. Instead of First Name it'll be Ticker
df_net = df_copy[ df_copy['Ticker'] == 'NFLX']
df_net

         Date Ticker  Daily_Change
4  2026-01-02   NFLX      0.033358
9  2026-01-05   NFLX     -0.005939

In [32]:
df_net = df_copy[ df_copy.Ticker == 'NFLX']
df_net

         Date Ticker  Daily_Change
4  2026-01-02   NFLX      0.033358
9  2026-01-05   NFLX     -0.005939

### Use .agg in order to just get the min, max, and mean for Daily_Change columns for df_net

In [33]:
#actors_df['Age'].agg(['min', 'max', 'mean'])   See example here for help
df_net['Daily_Change'].agg(['min', 'max', 'mean'])

min    -0.005939
max     0.033358
mean    0.013709
Name: Daily_Change, dtype: float64

# Taylor Swift Spotify

In [35]:
#Read in taylor_swift_spotify.csv file using pd. Use df_ts
df_ts = pd.read_csv("taylor_swift_spotify.csv")
df_ts

,name,album,release_date,track_number,id,uri,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,duration_ms
0,Fortnight (feat. Post Malone),THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,4/19/2024,1,6dODwocEuGzHAavXqTbwHv,spotify:track:6dODwocEuGzHAavXqTbwHv,0.50200,0.504,0.386,0.000015,0.0961,-10.976,0.0308,192.004,0.281,82,228965
1,The Tortured Poets Department,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,4/19/2024,2,4PdLaGZubp4lghChqp8erB,spotify:track:4PdLaGZubp4lghChqp8erB,0.04830,0.604,0.428,0.000000,0.1260,-8.441,0.0255,110.259,0.292,79,293048
2,My Boy Only Breaks His Favorite Toys,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,4/19/2024,3,7uGYWMwRy24dm7RUDDhUlD,spotify:track:7uGYWMwRy24dm7RUDDhUlD,0.13700,0.596,0.563,0.000000,0.3020,-7.362,0.0269,97.073,0.481,80,203801
3,Down Bad,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,4/19/2024,4,1kbEbBdEgQdQeLXCJh28pJ,spotify:track:1kbEbBdEgQdQeLXCJh28pJ,0.56000,0.541,0.366,0.000001,0.0946,-10.412,0.0748,159.707,0.168,82,261228
4,"So Long, London",THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,4/19/2024,5,7wAkQFShJ27V8362MqevQr,spotify:track:7wAkQFShJ27V8362MqevQr,0.73000,0.423,0.533,0.002640,0.0816,-11.388,0.3220,160.218,0.248,80,262974
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Our Song,Taylor Swift (Deluxe Edition),10/24/2006,11,1j6gmK6u4WNI33lMZ8dC1s,spotify:track:1j6gmK6u4WNI33lMZ8dC1s,0.11100,0.668,0.672,0.000000,0.3290,-4.931,0.0303,89.011,0.539,64,201106
578,I'm Only Me When I'm With You,Taylor Swift (Deluxe Edition),10/24/2006,12,7CzxXgQXurKZCyHz9ufbo1,spotify:track:7CzxXgQXurKZCyHz9ufbo1,0.00452,0.563,0.934,0.000807,0.1030,-3.629,0.0646,143.964,0.518,56,213053
579,Invisible,Taylor Swift (Deluxe Edition),10/24/2006,13,1k3PzDNjg38cWqOvL4M9vq,spotify:track:1k3PzDNjg38cWqOvL4M9vq,0.63700,0.612,0.394,0.000000,0.1470,-5.723,0.0243,96.001,0.233,54,203226
580,A Perfectly Good Heart,Taylor Swift (Deluxe Edition),10/24/2006,14,0YgHuReCSPwTXYny7isLja,spotify:track:0YgHuReCSPwTXYny7isLja,0.00349,0.483,0.751,0.000000,0.1280,-5.726,0.0365,156.092,0.268,53,220146
581,Teardrops on My Guitar - Pop Version,Taylor Swift (Deluxe Edition),10/24/2006,15,1hxLyjC9D9Jpw6EAPKqWv4,spotify:track:1hxLyjC9D9Jpw6EAPKqWv4,0.04020,0.459,0.753,0.000000,0.0863,-3.827,0.0537,199.997,0.483,55,179066

### Groupby album and get the mean values for each column using .mean(numeric_only=True). Save this as df_album

In [39]:
df_album = df_ts.groupby('album').mean(numeric_only=True)

In [41]:
df_album['duration_min'] = df_album['duration_ms']/60000

In [44]:
df_album.sort_values('duration_min')

,track_number,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,duration_ms,duration_min
album,,,,,,,,,,,,,
Midnights,7.0,0.391977,0.639615,0.408692,2.588854e-02,0.154038,-10.880615,0.103669,117.307538,0.222146,74.153846,203718.307692,3.395305
Lover,9.5,0.333743,0.658222,0.545222,7.330572e-04,0.115233,-8.013278,0.099117,119.972722,0.481444,75.944444,206187.833333,3.436464
Midnights (3am Edition),10.5,0.405685,0.620750,0.452550,1.701416e-02,0.139380,-10.587750,0.101970,124.007050,0.284670,62.850000,208463.200000,3.474387
Live From Clear Channel Stripped 2008,4.5,0.551250,0.548125,0.598875,0.000000e+00,0.144113,-5.067000,0.045125,137.639000,0.472125,32.250000,209469.375000,3.491156
Midnights (The Til Dawn Edition),12.0,0.395743,0.624348,0.472261,1.479520e-02,0.163200,-10.254609,0.095478,121.134000,0.273474,62.434783,210224.565217,3.503743
Taylor Swift (Deluxe Edition),8.0,0.182995,0.545267,0.664267,5.380000e-05,0.160773,-4.731667,0.032687,126.053800,0.426533,56.666667,213971.133333,3.566186
1989 (Deluxe),10.0,0.244620,0.633211,0.624842,7.042684e-04,0.203211,-7.924105,0.173453,127.033053,0.454211,49.000000,217139.368421,3.618989
1989 (Taylor's Version) [Deluxe],11.5,0.104170,0.626500,0.661182,1.082293e-03,0.147136,-7.140364,0.052536,119.519727,0.407191,63.000000,221731.818182,3.695530
1989 (Taylor's Version),11.0,0.108449,0.627571,0.662000,1.133831e-03,0.142857,-7.150333,0.050805,117.111714,0.417200,72.190476,222777.476190,3.712958
reputation,8.0,0.138515,0.657933,0.582867,4.378800e-05,0.152153,-7.672400,0.095120,127.540133,0.293400,75.733333,223020.000000,3.717000
1989,7.0,0.113175,0.650231,0.698769,9.060654e-04,0.154577,-6.236462,0.066254,118.552462,0.461908,52.692308,225220.307692,3.753672
folklore (deluxe version),9.0,0.717588,0.541941,0.415824,3.017124e-04,0.110465,-10.336059,0.039482,119.884412,0.361353,65.941176,236964.470588,3.949408
THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,16.0,0.572797,0.532419,0.457290,1.761029e-04,0.151039,-9.421839,0.056935,124.942452,0.314129,78.774194,237378.838710,3.956314
folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition],9.0,0.787971,0.551441,0.373412,1.086875e-03,0.125697,-10.620559,0.037721,116.098559,0.337676,49.058824,237713.852941,3.961898
folklore,8.5,0.710813,0.557500,0.425063,2.109544e-04,0.112625,-10.247063,0.040544,116.147000,0.380875,72.812500,238536.687500,3.975611
Fearless (International Version),8.5,0.134174,0.570812,0.635625,5.080750e-04,0.176175,-5.358125,0.032306,124.506875,0.393000,32.000000,240495.500000,4.008258
reputation Stadium Tour Surprise Song Playlist,23.5,0.160225,0.593130,0.653457,3.943676e-04,0.144372,-5.777891,0.040909,122.439978,0.446500,31.586957,242956.260870,4.049271
evermore,8.0,0.795333,0.518867,0.491333,2.335814e-02,0.114933,-9.822467,0.061100,117.479067,0.420600,66.400000,243014.000000,4.050233
Red,8.5,0.116116,0.622875,0.619563,2.448119e-03,0.133763,-7.129125,0.038619,109.684438,0.496938,45.000000,243462.125000,4.057702
evermore (deluxe version),9.0,0.794118,0.526824,0.494059,2.061718e-02,0.113588,-9.781588,0.057906,120.707294,0.433529,64.235294,243816.235294,4.063604
THE TORTURED POETS DEPARTMENT,8.5,0.463269,0.551312,0.452937,2.561262e-04,0.152150,-9.721938,0.068238,119.574187,0.308375,77.000000,244731.562500,4.078859
Fearless (Taylor's Version),13.5,0.214061,0.551038,0.639115,6.142308e-07,0.162354,-6.196538,0.037854,131.237231,0.421923,65.269231,245865.000000,4.097750
Red (Deluxe Edition),11.5,0.148799,0.633409,0.600773,1.802364e-03,0.119082,-7.380045,0.036582,110.296545,0.468145,44.954545,247294.318182,4.121572
Fearless (Platinum Edition),10.0,0.202937,0.575947,0.600316,2.171579e-06,0.159405,-5.706474,0.031895,123.088105,0.380368,43.157895,250874.105263,4.181235
Red (Taylor's Version),15.5,0.176866,0.576967,0.586900,1.489833e-04,0.124780,-7.014267,0.042250,124.361633,0.424600,67.233333,261327.666667,4.355461
Speak Now (Deluxe Package),11.5,0.226521,0.559000,0.659409,1.143727e-04,0.167023,-4.806909,0.035150,132.835682,0.429682,48.363636,275969.500000,4.599492
Speak Now (Taylor's Version),11.5,0.181765,0.555636,0.658273,2.500000e-07,0.135141,-4.658000,0.038409,130.155909,0.395836,69.454545,285638.681818,4.760645
Speak Now,7.5,0.186616,0.556000,0.659429,1.524043e-04,0.158621,-4.877286,0.038007,132.664786,0.443429,50.714286,287284.428571,4.788074
Speak Now World Tour Live,8.5,0.233802,0.441312,0.650250,1.006562e-05,0.774937,-7.129750,0.040881,122.616375,0.290250,41.312500,297121.187500,4.952020

In [42]:
df_album

,track_number,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,duration_ms,duration_min
album,,,,,,,,,,,,,
1989,7.0,0.113175,0.650231,0.698769,9.060654e-04,0.154577,-6.236462,0.066254,118.552462,0.461908,52.692308,225220.307692,3.753672
1989 (Deluxe),10.0,0.244620,0.633211,0.624842,7.042684e-04,0.203211,-7.924105,0.173453,127.033053,0.454211,49.000000,217139.368421,3.618989
1989 (Taylor's Version),11.0,0.108449,0.627571,0.662000,1.133831e-03,0.142857,-7.150333,0.050805,117.111714,0.417200,72.190476,222777.476190,3.712958
1989 (Taylor's Version) [Deluxe],11.5,0.104170,0.626500,0.661182,1.082293e-03,0.147136,-7.140364,0.052536,119.519727,0.407191,63.000000,221731.818182,3.695530
Fearless (International Version),8.5,0.134174,0.570812,0.635625,5.080750e-04,0.176175,-5.358125,0.032306,124.506875,0.393000,32.000000,240495.500000,4.008258
Fearless (Platinum Edition),10.0,0.202937,0.575947,0.600316,2.171579e-06,0.159405,-5.706474,0.031895,123.088105,0.380368,43.157895,250874.105263,4.181235
Fearless (Taylor's Version),13.5,0.214061,0.551038,0.639115,6.142308e-07,0.162354,-6.196538,0.037854,131.237231,0.421923,65.269231,245865.000000,4.097750
Live From Clear Channel Stripped 2008,4.5,0.551250,0.548125,0.598875,0.000000e+00,0.144113,-5.067000,0.045125,137.639000,0.472125,32.250000,209469.375000,3.491156
Lover,9.5,0.333743,0.658222,0.545222,7.330572e-04,0.115233,-8.013278,0.099117,119.972722,0.481444,75.944444,206187.833333,3.436464
Midnights,7.0,0.391977,0.639615,0.408692,2.588854e-02,0.154038,-10.880615,0.103669,117.307538,0.222146,74.153846,203718.307692,3.395305
Midnights (3am Edition),10.5,0.405685,0.620750,0.452550,1.701416e-02,0.139380,-10.587750,0.101970,124.007050,0.284670,62.850000,208463.200000,3.474387
Midnights (The Til Dawn Edition),12.0,0.395743,0.624348,0.472261,1.479520e-02,0.163200,-10.254609,0.095478,121.134000,0.273474,62.434783,210224.565217,3.503743
Red,8.5,0.116116,0.622875,0.619563,2.448119e-03,0.133763,-7.129125,0.038619,109.684438,0.496938,45.000000,243462.125000,4.057702
Red (Deluxe Edition),11.5,0.148799,0.633409,0.600773,1.802364e-03,0.119082,-7.380045,0.036582,110.296545,0.468145,44.954545,247294.318182,4.121572
Red (Taylor's Version),15.5,0.176866,0.576967,0.586900,1.489833e-04,0.124780,-7.014267,0.042250,124.361633,0.424600,67.233333,261327.666667,4.355461
Speak Now,7.5,0.186616,0.556000,0.659429,1.524043e-04,0.158621,-4.877286,0.038007,132.664786,0.443429,50.714286,287284.428571,4.788074
Speak Now (Deluxe Package),11.5,0.226521,0.559000,0.659409,1.143727e-04,0.167023,-4.806909,0.035150,132.835682,0.429682,48.363636,275969.500000,4.599492
Speak Now (Taylor's Version),11.5,0.181765,0.555636,0.658273,2.500000e-07,0.135141,-4.658000,0.038409,130.155909,0.395836,69.454545,285638.681818,4.760645
Speak Now World Tour Live,8.5,0.233802,0.441312,0.650250,1.006562e-05,0.774937,-7.129750,0.040881,122.616375,0.290250,41.312500,297121.187500,4.952020
THE TORTURED POETS DEPARTMENT,8.5,0.463269,0.551312,0.452937,2.561262e-04,0.152150,-9.721938,0.068238,119.574187,0.308375,77.000000,244731.562500,4.078859
THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,16.0,0.572797,0.532419,0.457290,1.761029e-04,0.151039,-9.421839,0.056935,124.942452,0.314129,78.774194,237378.838710,3.956314
Taylor Swift (Deluxe Edition),8.0,0.182995,0.545267,0.664267,5.380000e-05,0.160773,-4.731667,0.032687,126.053800,0.426533,56.666667,213971.133333,3.566186
evermore,8.0,0.795333,0.518867,0.491333,2.335814e-02,0.114933,-9.822467,0.061100,117.479067,0.420600,66.400000,243014.000000,4.050233
evermore (deluxe version),9.0,0.794118,0.526824,0.494059,2.061718e-02,0.113588,-9.781588,0.057906,120.707294,0.433529,64.235294,243816.235294,4.063604
folklore,8.5,0.710813,0.557500,0.425063,2.109544e-04,0.112625,-10.247063,0.040544,116.147000,0.380875,72.812500,238536.687500,3.975611
folklore (deluxe version),9.0,0.717588,0.541941,0.415824,3.017124e-04,0.110465,-10.336059,0.039482,119.884412,0.361353,65.941176,236964.470588,3.949408
folklore: the long pond studio sessions (from the Disney+ special) [deluxe edition],9.0,0.787971,0.551441,0.373412,1.086875e-03,0.125697,-10.620559,0.037721,116.098559,0.337676,49.058824,237713.852941,3.961898
reputation,8.0,0.138515,0.657933,0.582867,4.378800e-05,0.152153,-7.672400,0.095120,127.540133,0.293400,75.733333,223020.000000,3.717000
reputation Stadium Tour Surprise Song Playlist,23.5,0.160225,0.593130,0.653457,3.943676e-04,0.144372,-5.777891,0.040909,122.439978,0.446500,31.586957,242956.260870,4.049271

# Candy File

In [57]:
#Read in candy.csv and name it df_candy
df_candy = pd.read_csv('candy.csv')
df_candy

,Brand,Name,Serving/pkg,Oz/pkg,Calories,Total fat g,Saturated fat g,Cholesterol g,Sodium mg,Carbohydrate g,Dietary fiber g,Sugars g,Protein g,Vitamin A %RDI,Vitamin C %RDI,Calcium %RDI,Iron %RDI
0,M&M/Mars,Snickers Peanut Butter,1.0,2.00,310,20.0,7.0,5,150,28,1,23,6,0,0,6,2
1,Hershey,Cookies 'n' Mint,1.0,1.55,230,12.0,6.0,10,80,27,1,21,4,0,0,8,4
2,Hershey,Cadbury Dairy Milk,3.5,5.00,220,12.0,8.0,10,45,24,1,21,3,0,0,10,2
3,M&M/Mars,Snickers,3.0,3.70,170,8.0,3.0,5,85,21,1,17,3,0,0,2,0
4,Charms,Sugar Daddy,1.0,1.70,200,2.5,2.5,2,100,43,0,28,1,0,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,Hershey,Cadbury Caramello,3.5,5.00,190,9.0,6.0,10,55,25,0,19,2,0,0,8,2
71,Hershey,Milk Chocolate Almond,1.0,2.60,410,25.0,12.0,15,55,38,2,31,8,0,0,15,6
72,Hershey,Reese's Nutrageous,1.0,1.60,240,14.0,4.5,3,85,22,1,18,7,0,0,2,2
73,Leaf,Heath,2.0,2.80,210,13.0,7.0,20,180,25,0,24,2,6,0,4,2
74,Annabelle,Big Hunk,1.0,2.00,230,3.0,0.5,0,150,47,1,23,3,0,0,0,6

In [69]:
df_candy.groupby('Brand')['Protein g'].mean().sort_values(ascending=False)

Brand
Pearson           9.000000
Standard          7.000000
Nabisco           6.000000
Weider            6.000000
Hershey           4.137931
Myerson           4.000000
Leaf              3.666667
M&M/Mars          3.250000
Nestle            3.000000
Annabelle         2.600000
Sherwood          2.500000
Tobler            2.000000
Brown & Haley     2.000000
Adams & Brooks    1.000000
Bit-O-Honey       1.000000
Charms            1.000000
Tootsie           1.000000
Just Born         0.000000
Name: Protein g, dtype: float64

Let’s see which candy has the highest protein with filtering and sorting
Use groupby() to group the candy bars by company

# Office Employees File

In [70]:
import pandas as pd
df_office = pd.read_csv("office_employees.csv")

print(df_office)

           Employee               Title           Age  Gender  \
0     Creed Bratton     Quality Control            64    Male
1    Stanley Hudson     Sales Associate            59    Male
2     Michael Scott    Regional Manager            51    Male
3     Michael Scott    Regional Manager            51    Male
4     Phyllis Lapin     Sales Associate            51  Female
5    Oscar Martinez          Accountant            42    Male
6   Meredith Palmer    Vendor Relations            47  Female
7   Meredith Palmer    Vendor Relations            48  Female
8    Dwight Schrute     Sales Associate            36       M
9    Dwight Schrute     Sales Associate            36       M
10     Kevin Malone           Accountnt            39    Male
11      Pam Beasley        Receptionist            31  Female
12      Jim Halpert     Sales Associate            31    Male
13    Angela Palmer          Accountant            33  Female
14  Toby Flenderson     Human Resources            45    Male
15     Kelly Kapoor    Customer Service  Twenty-eight       F
16      Ryan Howard  Temporary Employee            24       M

             Salary Commission            HireDate
0   42,000 per year          N           22-Mar-85
1   53,000 per year          Y            2-Feb-86
2   58,000 per year          N           12-Nov-87
3   58,000 per year          N           12-Nov-87
4       51 per year          Y           27-Apr-90
5   46,000 per year          N  September 13, 1996
6   41,500 per year          N            4-Aug-99
7   41,500 per year          N            4-Aug-99
8   46,500 per year          Y           13-Jan-01
9   46,500 per year          Y           13-Jan-01
10  41,000 per year          N           21-Jan-02
11  39,000 per year          N           16-Jul-03
12      44 per year          Y            8-Oct-03
13  43,000 per year          N           19-Jan-04
14  42,500 per year          N            6-Mar-25
15  38,000 per year          N           18-Jul-06
16  31,000 per year          N            1-Sep-06

In [74]:
#Use .duplicated to find the duplicate records of office employees. How many are there?
duplicates = [df_office.duplicated(keep=False)]
duplicates

[0     False
 1     False
 2      True
 3      True
 4     False
 5     False
 6     False
 7     False
 8      True
 9      True
 10    False
 11    False
 12    False
 13    False
 14    False
 15    False
 16    False
 dtype: bool]

In [79]:
#Use .drop_duplicates to drop them.
df_off = df_office.drop_duplicates()

In [80]:
# Change the age column to numeric using df_off['Age'] = pd.to_numeric(df_off['Age'], errors='coerce')
df_off['Age'] = pd.to_numeric(df_off['Age'], errors='coerce')

### Find which row has NaN using .isna.  Use .fillna() to make that missing value 28.

In [83]:
df_off['Age'].isna()

0     False
1     False
2     False
4     False
5     False
6     False
7     False
8     False
10    False
11    False
12    False
13    False
14    False
15     True
16    False
Name: Age, dtype: bool

In [84]:
df_off['Age'].fillna(28)

0     64.0
1     59.0
2     51.0
4     51.0
5     42.0
6     47.0
7     48.0
8     36.0
10    39.0
11    31.0
12    31.0
13    33.0
14    45.0
15    28.0
16    24.0
Name: Age, dtype: float64