# Data Programming in Python | BAIS:6040
# Notebook Demonstration 5.7 - Handling Missing Values

## Handling Missing Values in a Dataframe

In many cases, you need to handle null values, or missing values, in a dataframe. There are two approaches you can consider to handle null values:
- Drop the rows with null values (--> easy but lose data)
- Fill the null values with something else (--> do not lose data but careful what to fill with)

In [1]:
import pandas as pd
import numpy as np
from seaborn import load_dataset

In [2]:
df = load_dataset("titanic")
df = df[["survived", "pclass", "sex", "age", "fare"]].sample(n=20, random_state=3)
df

     survived  pclass     sex   age      fare
395         0       3    male  22.0    7.7958
85          1       3  female  33.0   15.8500
201         0       3    male   NaN   69.5500
542         0       3  female  11.0   31.2750
702         0       3  female  18.0   14.4542
51          0       3    male  21.0    7.8000
237         1       2  female   8.0   26.2500
548         0       3    male  33.0   20.5250
527         0       1    male   NaN  221.7792
157         0       3    male  30.0    8.0500
144         0       2    male  18.0   11.5000
48          0       3    male   NaN   21.6792
887         1       1  female  19.0   30.0000
239         0       2    male  33.0   12.2750
270         0       1    male   NaN   31.0000
575         0       3    male  19.0   14.5000
627         1       1  female  21.0   77.9583
164         0       3    male   1.0   39.6875
525         0       3    male  40.5    7.7500
498         0       1  female  25.0  151.5500

In [ ]:
df.info()

In [ ]:
df.isnull()        # equivalent to .isna()

pandas.DataFrame.isnull: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isnull.html

The <b>isnull</b> method returns which entries in a dataframe are null.

In [ ]:
df.isnull().any()

In [ ]:
df.isnull().any(axis=1)

pandas.DataFrame.any: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.any.html

The <b>any</b> method returns whether any element is True over the specified axis.

In [ ]:
mask = df.isnull().any(axis=1)
df[mask]     # Returns all rows with any null values.

In [13]:
df1 = df.copy()
df1

     survived  pclass     sex   age      fare
395         0       3    male  22.0    7.7958
85          1       3  female  33.0   15.8500
201         0       3    male   NaN   69.5500
542         0       3  female  11.0   31.2750
702         0       3  female  18.0   14.4542
51          0       3    male  21.0    7.8000
237         1       2  female   8.0   26.2500
548         0       3    male  33.0   20.5250
527         0       1    male   NaN  221.7792
157         0       3    male  30.0    8.0500
144         0       2    male  18.0   11.5000
48          0       3    male   NaN   21.6792
887         1       1  female  19.0   30.0000
239         0       2    male  33.0   12.2750
270         0       1    male   NaN   31.0000
575         0       3    male  19.0   14.5000
627         1       1  female  21.0   77.9583
164         0       3    male   1.0   39.6875
525         0       3    male  40.5    7.7500
498         0       1  female  25.0  151.5500

pandas.DataFrame.copy: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.copy.html

The <b>copy</b> method makes a copy of a dataframe.

In [14]:
df1 = df1.dropna()

In [15]:
df1

     survived  pclass     sex   age      fare
395         0       3    male  22.0    7.7958
85          1       3  female  33.0   15.8500
542         0       3  female  11.0   31.2750
702         0       3  female  18.0   14.4542
51          0       3    male  21.0    7.8000
237         1       2  female   8.0   26.2500
548         0       3    male  33.0   20.5250
157         0       3    male  30.0    8.0500
144         0       2    male  18.0   11.5000
887         1       1  female  19.0   30.0000
239         0       2    male  33.0   12.2750
575         0       3    male  19.0   14.5000
627         1       1  female  21.0   77.9583
164         0       3    male   1.0   39.6875
525         0       3    male  40.5    7.7500
498         0       1  female  25.0  151.5500

In [ ]:
df1.dropna(inplace=True)

In [ ]:
df1.shape

pandas.DataFrame.dropna: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html

The <b>dropna</b> method drops all rows with any null values in a dataframe. Note that it returns a copy of the target dataframe.

In [3]:
df1 = df.copy()

In [7]:
df1 = df1.dropna(how="any")
df1

AttributeError: 'NoneType' object has no attribute 'dropna'

In [6]:
display(df1)

None

Note that the <b>dropna</b> method drops the entire row if there is any null value in the row.

In [ ]:
len(df1)

In [ ]:
df2 = df.copy()
df2

In [ ]:
df2 = df2.dropna(how="all")
df2

If you set the parameter `how` to *all*, it drops the row when all values in the row are null. Default is any.

In [ ]:
df3 = df.copy()
df3

In [ ]:
df3.sex.mode()

In [ ]:
df3

In [ ]:
df3.age.mean()

In [ ]:
df3.age.values.mean()

In [ ]:
df3.age.mean(skipna=True)

In [ ]:
df3.age.mean().round()

In [ ]:
df3.age.fillna(df3.age.mean().round())

In [ ]:
df3.age = df3.age.fillna(df3.age.mean().round())

In [ ]:
df3

In [ ]:
df3 = df.copy()

In [ ]:
df3.age.fillna(value=0)

In [ ]:
df3

In [ ]:
df3.age = df3.age.fillna(value=0)        # Targeted at a specific column
df3

pandas.DataFrame.fillna: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html

You should determine whether you are going to deal with the whole dataframe or one or more specific columns in the dataframe. The <b>fillna</b> method fills all the null values with a value specified in the `value` parameter.

In [ ]:
df4 = df.copy()

In [ ]:
df4 = df4.fillna(value={"survived": df.survived.mean(), "pclass": df.pclass.mean(), "sex": "unknown",
                        "age": df.age.min(), "fare": df.fare.median()})
df4

Instead of filling all null values with the same value, you can fill with different values depending on the column, specifying one by one the columns and the values to be replaced in a dictionary.